+incdir+hardware/soc/rtl/include
+hardware/soc/rtl/include/axi/typedef.svh
+hardware/soc/rtl/include/axi/assign.svh
+hardware/soc/rtl/include/common_cells/assertions.svh
+hardware/soc/rtl/include/common_cells/registers.svh
hardware/cpu/cpu_cv32e40p/include/cv32e40p_pkg.sv
hardware/cpu/cpu_cv32e40p/include/cv32e40p_apu_core_pkg.sv
hardware/cpu/cpu_cv32e40p/include/cv32e40p_fpu_pkg.sv
hardware/soc/rtl/include/my_soc_pkg.sv
hardware/soc/rtl/axi/axi_pkg.sv
hardware/soc/rtl/common_cells/cf_math_pkg.sv
hardware/soc/rtl/debug/dm_pkg.sv
hardware/soc/rtl/axi/axi_intf.sv
hardware/soc/rtl/axi/addr_decode.sv
hardware/soc/rtl/axi/axi_xbar.sv
hardware/soc/rtl/axi/axi_demux.sv
hardware/soc/rtl/axi/axi_mux.sv
hardware/soc/rtl/axi/axi_id_prepend.sv
hardware/soc/rtl/axi/axi_err_slv.sv
hardware/soc/rtl/axi/axi_atop_filter.sv
hardware/soc/rtl/axi/axi_adapter.sv
hardware/soc/rtl/axi/axi2mem.sv
hardware/soc/rtl/common_cells/fifo_v2.sv
hardware/soc/rtl/common_cells/fifo_v3.sv
hardware/soc/rtl/common_cells/rr_arb_tree.sv
hardware/soc/rtl/common_cells/stream_register.sv
hardware/soc/rtl/common_cells/spill_register.sv
hardware/soc/rtl/common_cells/spill_register_flushable.sv
hardware/soc/rtl/common_cells/counter.sv
hardware/soc/rtl/common_cells/delta_counter.sv
hardware/soc/rtl/common_cells/lzc.sv
hardware/soc/rtl/common_cells/cdc_2phase.sv
hardware/soc/rtl/clk_rst/pulp_clk_cells.sv
hardware/soc/rtl/clk_rst/cluster_clk_cells.sv
hardware/soc/rtl/clk_rst/tc_clk.sv
hardware/soc/rtl/clk_rst/rstgen_bypass.sv
hardware/soc/rtl/clk_rst/rstgen.sv
hardware/soc/rtl/clk_rst/cv32e40p_fpga_clock_gate.sv
hardware/soc/rtl/mem/bootram.sv
hardware/soc/rtl/debug/debug_rom.sv
hardware/soc/rtl/debug/dm_csrs.sv
hardware/soc/rtl/debug/dm_mem.sv
hardware/soc/rtl/debug/dm_sba.sv
hardware/soc/rtl/debug/dm_top.sv
hardware/soc/rtl/debug/dmi_cdc.sv
hardware/soc/rtl/debug/dmi_jtag_tap.sv
hardware/soc/rtl/debug/dmi_jtag.sv
hardware/soc/rtl/mem/sram_ff.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_ff_one.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_fifo.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_aligner.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_compressed_decoder.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_decoder.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_controller.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_int_controller.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_prefetch_controller.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_prefetch_buffer.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_obi_interface.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_if_stage.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_id_stage.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_hwloop_regs.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_load_store_unit.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_ex_stage.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_apu_disp.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_alu_div.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_alu.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_mult.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_popcnt.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_register_file_ff.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_sleep_unit.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_cs_registers.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_core.sv
hardware/cpu/cpu_cv32e40p/rtl/cv32e40p_top.sv
hardware/soc/rtl/mem/my_mainmem.sv
hardware/soc/rtl/dma/npu_dma.sv
hardware/npu/rtl/ws_pe.sv
hardware/npu/rtl/ws_systolic_array.sv
hardware/npu/rtl/matrix_unit.sv
hardware/npu/rtl/vector_unit.sv
hardware/npu/rtl/requant_unit.sv
hardware/npu/rtl/reduction_sum_unit.sv
hardware/npu/rtl/conv_window_addr_gen.sv
hardware/npu/rtl/conv2d_engine.sv
hardware/npu/rtl/maxpool2x2_engine.sv
hardware/npu/rtl/global_sum_pool_engine.sv
hardware/npu/rtl/global_avg_pool_engine.sv
hardware/npu/rtl/tinycnn8_npu_top.sv
hardware/soc/rtl/npu/tinycnn8_npu_mmio_wrapper.sv
hardware/soc/rtl/my_npu_subsystem.sv
hardware/soc/rtl/my_soc_top.sv
hardware/soc/sim/tb/chipdesign_soc_tb.sv
hardware/soc/sim/tb/chipdesign_dma_tb.sv
