#!/usr/bin/env python3
"""Generate the integrated CPU -> TinyCNN-8 NPU smoke-test image.

The hand-written RV32I program loads an all-zero model and input through the
production MMIO windows, starts one four-class inference, checks four zero
INT32 logits, clears completion, and writes PASS/FAIL to the SRAM magic word.
"""

REGS = {
    'zero': 0, 'ra': 1, 'sp': 2, 'gp': 3, 'tp': 4,
    't0': 5, 't1': 6, 't2': 7, 's0': 8, 's1': 9,
    'a0': 10, 'a1': 11, 'a2': 12, 'a3': 13, 'a4': 14,
    'a5': 15, 'a6': 16, 'a7': 17, 's2': 18, 's3': 19,
    's4': 20, 's5': 21, 's6': 22, 's7': 23, 's8': 24,
    's9': 25, 's10': 26, 's11': 27, 't3': 28, 't4': 29,
    't5': 30, 't6': 31,
}


def reg(name):
    return REGS[name]


def imm12(value):
    return value & 0xFFF


def lui(rd, value):
    return ((value & 0xFFFFF) << 12) | (reg(rd) << 7) | 0b0110111


def addi(rd, rs1, value):
    return (imm12(value) << 20) | (reg(rs1) << 15) | (reg(rd) << 7) | 0b0010011


def sw(rs2, value, rs1):
    value = imm12(value)
    return (((value >> 5) & 0x7F) << 25) | (reg(rs2) << 20) | \
           (reg(rs1) << 15) | (0b010 << 12) | ((value & 0x1F) << 7) | 0b0100011


def lw(rd, value, rs1):
    return (imm12(value) << 20) | (reg(rs1) << 15) | \
           (0b010 << 12) | (reg(rd) << 7) | 0b0000011


def andi(rd, rs1, value):
    return (imm12(value) << 20) | (reg(rs1) << 15) | \
           (0b111 << 12) | (reg(rd) << 7) | 0b0010011


def branch(funct3, rs1, rs2, target, pc):
    value = target - pc
    return (((value >> 12) & 1) << 31) | (((value >> 5) & 0x3F) << 25) | \
           (reg(rs2) << 20) | (reg(rs1) << 15) | (funct3 << 12) | \
           (((value >> 1) & 0xF) << 8) | (((value >> 11) & 1) << 7) | 0b1100011


def beq(rs1, rs2, target, pc):
    return branch(0b000, rs1, rs2, target, pc)


def bne(rs1, rs2, target, pc):
    return branch(0b001, rs1, rs2, target, pc)


def jump(target, pc):
    value = target - pc
    return (((value >> 20) & 1) << 31) | (((value >> 1) & 0x3FF) << 21) | \
           (((value >> 11) & 1) << 20) | (((value >> 12) & 0xFF) << 12) | 0b1101111


def build():
    base = 0x80000000
    pc = base
    labels = {}
    ops = []

    def mark(name):
        labels[name] = pc

    def op(name, *args):
        nonlocal pc
        ops.append((name, args))
        pc += 4

    # t0=NPU base, t6=magic-region anchor. Mark software as running.
    op('lui', 't0', 0x70000)
    op('lui', 't6', 0x80002)
    op('lui', 't1', 0x12345)
    op('addi', 't1', 't1', 0x678)
    op('sw', 't1', -32, 't6')

    # One INT8 activation is stored in the low byte of each 32-bit MMIO word.
    op('lui', 't2', 0x70001)
    op('addi', 't3', 'zero', 320)
    mark('clear_input')
    op('sw', 'zero', 0, 't2')
    op('addi', 't2', 't2', 4)
    op('addi', 't3', 't3', -1)
    op('bne', 't3', 'zero', 'clear_input')

    # Clear all 256 packed 64-bit weight words as 512 sequential word writes.
    op('lui', 't2', 0x70002)
    op('addi', 't3', 'zero', 512)
    mark('clear_weights')
    op('sw', 'zero', 0, 't2')
    op('addi', 't2', 't2', 4)
    op('addi', 't3', 't3', -1)
    op('bne', 't3', 'zero', 'clear_weights')

    # Parameter staging resets to zero. Commit it to Conv1/Conv2/GAP/FC.
    op('lui', 't2', 0x70003)
    for offset in (0x060, 0x160, 0x260, 0x360):
        op('sw', 'zero', offset, 't2')

    # Four classes, start inference, and enable the completion IRQ.
    op('addi', 't1', 'zero', 4)
    op('sw', 't1', 0x008, 't0')
    op('addi', 't1', 'zero', 3)
    op('sw', 't1', 0x000, 't0')

    mark('poll_done')
    op('lw', 't1', 0x004, 't0')
    op('andi', 't2', 't1', 8)
    op('bne', 't2', 'zero', 'fail')
    op('andi', 't2', 't1', 4)
    op('beq', 't2', 'zero', 'poll_done')

    # An all-zero model must produce four zero logits.
    for offset in (0x010, 0x014, 0x018, 0x01C):
        op('lw', 't2', offset, 't0')
        op('bne', 't2', 'zero', 'fail')

    # Clear done while retaining IRQ enable, then check that done is low.
    op('addi', 't1', 'zero', 6)
    op('sw', 't1', 0x000, 't0')
    op('lw', 't1', 0x004, 't0')
    op('andi', 't1', 't1', 4)
    op('bne', 't1', 'zero', 'fail')

    op('lui', 't1', 0xC0DEC)
    op('addi', 't1', 't1', 0x0DE)
    op('sw', 't1', -32, 't6')
    mark('done')
    op('j', 'done')

    mark('fail')
    op('lui', 't1', 0xDEADC)
    op('addi', 't1', 't1', -0x111)
    op('sw', 't1', -32, 't6')
    op('j', 'done')

    encoders = {
        'lui': lui, 'addi': addi, 'sw': sw, 'lw': lw,
        'andi': andi, 'beq': beq, 'bne': bne,
    }
    pc = base
    output = ["// Auto-generated by gen_hex.py: complete TinyCNN-8 MMIO smoke test"]
    for name, args in ops:
        if name in ('beq', 'bne'):
            inst = encoders[name](args[0], args[1], labels[args[2]], pc)
        elif name == 'j':
            inst = jump(labels[args[0]], pc)
        else:
            inst = encoders[name](*args)
        output.append(f"{inst:08x}")
        pc += 4
    return '\n'.join(output) + '\n'


if __name__ == '__main__':
    print(build(), end='')
